# Run lint

name: lint_and_test

on:
  push:
    branches:
      - 'main'
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3

      - name: setup env
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          python -m pip install poetry==1.1.15
          python -m poetry install

      - name: lint codes
        run: python -m poetry run flake8 mlflow_logger_ext/

      - name: run-pytest
        run: python -m poetry run pytest mlflow_logger_ext/